name: Generate Lua Database

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify Python version

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; fi
        echo "Dependencies installed"

    - name: Verify Python Installation and Path
      run: |
        python --version
        pip list  # Verify installed packages (to check if requirements were installed correctly)

    - name: Run database generation script
      run: |
        echo "Running the database generation script"
        python hf2_generate_lua_db.py  # Run your script to process the dumps and output the CSV
      continue-on-error: true  # Let’s add this here temporarily for debugging

    - name: Check script output (Debugging)
      run: |
        echo "Listing files to confirm script output"
        ls -l  # This will list files and help confirm if the output CSV files were created

    - name: Commit and Push CSV File
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add *.csv
        # Only commit if there are changes to be made
        git diff --cached --quiet || git commit -m "Auto-generated Lua database from latest dumps"
        # Attempt to push changes, allow failure if no changes were made
        git push || echo "No changes to push"
      continue-on-error: true
